import { getServerSession } from "next-auth";
import LoginBtn from "./LoginBtn";
import "./globals.css";
import Link from "next/link";
import { authOptions } from "../../pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          <LoginBtn session={session} />
        </div>
        {children}
      </body>
    </html>
  );
}
